### ISSUE TITLE
AttributeError: CLearnCurve instance has no attribute 'tn_mc'

### ISSUE THREAD

**Issue by petteriTeikari** [seung-lab/znn-release#35]
I get the following error with train.py when saving the network:

```python

save as  ../../../znnData/experiments/VD2D3D_tanh_even/net_187451.h5
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    main( sys.argv[1] )
  File "train.py", line 179, in main
    lc.save( pars, elapsed )
  File "./znn-release/python/zstatistics.py", line 234, in save
    f.create_dataset('/train/mc',  data=self.tn_mc )
AttributeError: CLearnCurve instance has no attribute 'tn_mc'

```

**Comment by jingpengwu** [comment]
Just pushed a fix.
I'll move my experimental code to `malis` branch and keep the `master` clean.

**Comment by petteriTeikari** [comment]
I pulled again, and now it was with this error:

```python
defining initial dict
performing consolidation
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    main( sys.argv[1] )
  File "train.py", line 31, in main
    lc = zstatistics.CLearnCurve( pars['train_load_net'] )
  File "/home/petteri/Dropbox/znn-release/python/zstatistics.py", line 26, in __init__
    self._read_curve( fname )
  File "/home/petteri/Dropbox/znn-release/python/zstatistics.py", line 65, in _read_curve
    self.tn_mc = lis()
NameError: global name 'lis' is not defined
```

And when running the train.py with the default `config.cfg` I get:

```
construct the network class using the edges and nodes...
if unseccessful, please check the network config file (networks/XXX.znn).
Segmentation fault (core dumped)
```

**Comment by jingpengwu** [comment]
Sorry for the problems. I tested this fix. Please pull and try again.
The segmentation fault may due to the missing file of N4.znn, which was added now. 

Hopefully, after fixing these issues, I'll move to malis branch keep the master stable.
