### ISSUE TITLE
Forward

### ISSUE THREAD

**Issue by petteriTeikari** [seung-lab/znn-release#42]
I pulled your changes yesterday, and previously the forward pass was working just fine, but now I got the following during the processing:

```python
Output patch #144 of 245
Output patch #145 of 245

Traceback (most recent call last):
  File "forward.py", line 214, in <module>
    main( argv[1] )
  File "forward.py", line 200, in main
    output_volume = config_forward_pass( config, params, verbose=True, sample_ids=[sample_id])
  File "forward.py", line 75, in config_forward_pass
    verbose=True)
  File "forward.py", line 126, in generate_full_output
    input_patches, junk = Dataset.get_next_patch()
  File "znn-release/python/front_end/zsample.py", line 193, in get_next_patch
    outputs[name] = img.get_next_patch()
  File "znn-release/python/front_end/zdataset.py", line 201, in get_next_patch
    patch = self.get_patch(self.patch_id)
  File "znn-release/python/front_end/zdataset.py", line 188, in get_patch
    patch_beginnings = self.patch_bounds[patch_id][0]
IndexError: list index out of range
```

Any idea of what is going on there?

**Comment by jingpengwu** [comment]
I think that I have found the problem and fix it. The forward pass need layer specific field of view. I have added it. Please checkout the `reorganize` branch and try again :)

**Comment by jingpengwu** [comment]
the `forward` pass fix was merged to `master`.
